source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MQTTClientTests' do
	platform :ios, '8.0'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
	pod 'mqttc/WebsocketL', :path => '..'
end

target 'MQTTClientTVTests' do
	platform :tvos, '9.0'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
	pod 'mqttc/WebsocketL', :path => '..'
end

target 'MQTTClientOSXTests' do
	platform :osx, '10.10'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
	pod 'mqttc/WebsocketL', :path => '..'
end

target 'MQTTClientOSXTestsNOLumberjack' do
	platform :osx, '10.10'
	pod 'mqttc/Min', :path => '..'
	pod 'mqttc/Manager', :path => '..'
	pod 'mqttc/Websocket', :path => '..'
end
