source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MQTTClientNativeTests' do
	platform :ios, '17'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
end

target 'MQTTClientTVTests' do
	platform :tvos, '17'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
end

target 'MQTTClientOSXTests' do
	platform :osx, '14'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
end

