source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MQTTClientNativeTests' do
	platform :ios, '16'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
end

target 'MQTTClientOSXTests' do
	platform :osx, '13'
	pod 'CocoaLumberjack'
	pod 'mqttc/MinL', :path => '..'
	pod 'mqttc/ManagerL', :path => '..'
end

